// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPhJi37DmpaJGlJHnu5mia3D1-sCxifzo',
    appId: '1:192983514869:android:c26db434f32f3c87074fbc',
    messagingSenderId: '192983514869',
    projectId: 'graduation-project-73ced',
    storageBucket: 'graduation-project-73ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgG_8H9ObHC0Pia51cyFfdjdGDYxEmXt0',
    appId: '1:192983514869:ios:55155b892e4232d4074fbc',
    messagingSenderId: '192983514869',
    projectId: 'graduation-project-73ced',
    storageBucket: 'graduation-project-73ced.appspot.com',
    androidClientId: '192983514869-tke9292ollgktpndbfmkn4ho2msb337i.apps.googleusercontent.com',
    iosClientId: '192983514869-4pvksbfvbb70bsodol7clt5stovicm9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientapp',
  );
}
